
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - npm install -g serverless@2.21.1
  - cd backend && npm install

# Scripts to be run such as tests
before_script:
  - sls config credentials --provider aws --key $aws_access_key_id --secret $aws_secret_access_key
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - echo "==================== Deploy Backend ===================="
  - sls -version
  - sls deploy -v
  - echo "==================== Deploy Frontend ===================="
  - cd ../client
  - docker --version
  - docker build -t todo-app-client .
  - docker tag todo-app-client linh626688/todo-app-client:latest
  - docker push linh626688/todo-app-client:latest
